databases:
  - name: postgres
    ipAllowList: []
    plan: free

services:
  - type: web
    name: breakable-toy
    env: node
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "yarn start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString